### ISSUE TITLE
No effect using `num_stages` in max pooling

### ISSUE THREAD

**Issue by Jokeren** [kakaobrain/trident#1]
## 🐞 Describe the bug

https://github.com/kakaobrain/trident/blob/ce17900e0ed53d27c8d7b99f467b1f5c649c33a7/trident/operation/max_pool2d.py#L42

It actually doesn't have any effect in this kernel. IIUC, you intended to unroll the loop and overlap load/compute? It needs to be done manually for now.

**Comment by daemyung** [comment]
@Jokeren Yes exactly and thanks for your comment. Currently the performance of `MaxPool2d` is very slow when the kernel size is very small. Now I'm trying to batch.

**Comment by daemyung** [comment]
This issue is resolved by [changes](https://github.com/kakaobrain/trident/commit/1609f3c8a97872c01d18fee9a450a16030e1b4ba).
