### ISSUE TITLE
Could dropout be included here as an option?

### ISSUE THREAD

**Issue by BruceDai003** [kakaobrain/trident#120]
https://github.com/kakaobrain/trident/blob/3c2067bac5fb917cbec5f12a62b2fe9524c32e91/trident/kernel/attention.py#L46

**Comment by kakao-steve-ai** [comment]
@BruceDai003 Thanks for reporting an issue. Dropout of Attention has not been implemented yet. I will let you know when it is implemented.

**Comment by daemyung** [comment]
@BruceDai003 It's implemented.
