### ISSUE TITLE
Bias in Attention isn't supported

### ISSUE THREAD

**Issue by hypnopump** [kakaobrain/trident#128]
## 🙋 Describe the feature

I would like to have the `bias` argument [in the attention API](https://github.com/kakaobrain/trident/blob/main/trident/operation/attention.py#L74), as it is used in many models and would favour Trident adoption. 

## 💬 Additional context

In the following equation, `l` denotes *layer* and `h` denotes *head*: 
<img width="469" alt="Captura de Pantalla 2023-09-14 a las 13 21 06" src="https://github.com/kakaobrain/trident/assets/16491423/7bbd7b7c-00f4-44d2-a876-38df7be9d253">

**Comment by daemyung** [comment]
@hypnopump Hi, I will let you know when this feature is added.

**Comment by hypnopump** [comment]
Thanks! I have found this related example: 
* [`triton flash attention v1 + bias`](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_triton.py#L70)

**Comment by shiqingzhangCSU** [comment]
Hi！I also want flash attention2 with bias. Is there any progress on this feature currently? Thanks！

**Comment by daemyung** [comment]
@shiqingzhangCSU Sorry this is not a high priority right now. I will let you know when it's ready.

**Comment by daemyung** [comment]
@hypnopump @shiqingzhangCSU Your request have been completed. Enjoy Trident!

**Comment by shiqingzhangCSU** [comment]
> @hypnopump @shiqingzhangCSU Your request have been completed. Enjoy Trident!

Thanks! Is this implementation flash attention v2?
