### ISSUE TITLE
Low performance of Conv2d

### ISSUE THREAD

**Issue by jaedochung** [kakaobrain/trident#36]
## 🐞 Describe the bug

According to https://github.com/kakaobrain/trident/wiki/Performance#conv2d, trident is up to 40x slower than torch. Is the graph (and the table below) there correct? Or could it be a bug in the graph?

**Comment by daemyung** [comment]
@jaedochung The graph is correct. Conv2d isn't optimized well. We will optimze Conv2d as soon as possible.

**Comment by daemyung** [comment]
Sorry, we have decided to deprecate Conv2d. See #118. We will back Conv2d with performance and features.
